[project]
name = "ml-backend"
version = "0.1.0"
description = "Machine Learning Backend for Chrome Extension"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "torch>=2.5.1",
    "transformers>=4.47.1",
    "uvicorn>=0.34.0",
]
